name: publish

on:
  push:
    branches:
      - main
    paths:
      - '*/PKGBUILD'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0

      - name: Find updated package
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail

          echo "pkgbuild=$(git diff --name-only HEAD HEAD~1 "*/.SRCINFO" | head -1 | xargs dirname)" >> $GITHUB_ENV

      - name: Publish package
        uses: KSXGitHub/github-actions-deploy-aur@f253a99125c1ca6bf2451d5a126fe04214d884bd # v2.7.1
        if: ${{ env.pkgbuild != '' }}
        with:
          pkgname: ${{ env.pkgbuild }}
          pkgbuild: ${{ env.pkgbuild }}/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
